spring:
  datasource:
    username: root
    password: 664243
    url: jdbc:mysql://47.99.165.122:3306/liyang?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  ##配置项目访问名
  servlet:
    context-path: /liyang
mybatis:
    # 映射mapper .xml文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
    #实体类映射位置
  type-aliases-package: com.liyang.entity
    # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
