spring:
  datasource:
    username: root
    password: 664243
    url: jdbc:mysql://47.99.165.122:3306/liyang?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
  ##配置项目访问名
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.99.165.122
    # Redis端口号
    port: 6379
    # Redis 密码
    password:
    # 连接池
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
mybatis:
    # 映射mapper .xml文件位置
  mapper-locations: classpath:mapper/*Mapper.xml,classpath:mapper/music/*Mapper.xml,classpath:mapper/video/*Mapper.xml
    #实体类映射位置
  type-aliases-package: com.liyang.entity
    # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置日志
logging:
  level:
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
  #采用相对路径方式将日志文件输出到【log/myspringboot.log】
  file: E:/log/springboot.log
  #采用绝对路径方式将日志文件输出到【/Users/wang/Downloads/myspringboot.log】
  #file: /Users/wang/Downloads/myspringboot.log
server:
  port: 8888
  servlet:
    context-path: /liyang